### ISSUE TITLE
Round to decimals instead of scientific notation

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [ferraridamiano/units_converter#17]
Is there a possibility to round the converted value to decimals instead of scientific notation when inputting significant figures?

Thanks!

**Comment by ferraridamiano** [comment]
Thanks for your suggestion

**Comment by ferraridamiano** [comment]
@YarostheLaunchpadder 
Fixed and published in 1.2.0

**Comment by YarostheLaunchpadder** [comment]
Thank you so much!
