### ISSUE TITLE
[BUG] conversion bar to Pascal is incorrect

### ISSUE THREAD

**Issue by VibrantTreeStump** [ferraridamiano/units_converter#25]
**Describe the bug**
1 bar is converted to 100007.775 Pa and 1000.07775 hPa, which is incorrect. 1 bar = 10^5 Pa = 10^3 hPa

**Screenshots / gif**
![Screenshot_20220602-232752.png](https://user-images.githubusercontent.com/82000085/171742041-b8b8a65f-fd86-4abf-8b8f-d19b11c745a5.png)

**Comment by ferraridamiano** [comment]
Thank you @VibrantTreeStump I transferred this issue here (the unit conversion library used by converter NOW
