### ISSUE TITLE
[new-unit] RTD to Temperature conversion 

### ISSUE THREAD

**Issue by AbuBakar988** [ferraridamiano/units_converter#35]
**Description**
Temperature sensor RTD (PP100 ohms) to temperature (Celsius, Fahrenheit) converter.

**Units to be added**
| Unit name | Property | Reference to the conversion formula                |
| ----------| -------- | -------------------------------------------------- |
| Ohms  | Pt100   | [link](https://us.flukecal.com/pt100-calculator)     |
| Celsius     | Temperature     | / |
| Fahrenheit       | Temperature | /                                                  |

**Comment by ferraridamiano** [comment]
Well this looks like more a feature for a tool and not for a unit converter. I think that it is not appropriate for this package
