### ISSUE TITLE
[new-unit] Lux <-> Foot-candle

### ISSUE THREAD

**Issue by denxorz** [ferraridamiano/units_converter#37]
**Description**
I would like to have the conversion between the metric 'Lux' and the imperial 'Foot-candle'. This is used as a parameter in plant realted measurements.

**Units to be added**
| Unit name | Property | Reference to the conversion formula                |
| ----------| -------- | -------------------------------------------------- |
| Lux | Illuminance| [link](https://en.wikipedia.org/wiki/Lux)     |
| Foot-candle| Illuminance| [link](https://en.wikipedia.org/wiki/Foot-candle) and [link](https://github.com/convert-units/convert-units/blob/main/src/definitions/illuminance.ts) |

**Comment by ferraridamiano** [comment]
Thank you! Feel free to send a PR! It's pretty easy and I could review it
