### ISSUE TITLE
[BUG] Numeral_System conversion is not working

### ISSUE THREAD

**Issue by krutarth-vaishnav** [ferraridamiano/units_converter#41]
## Bug description
When I Convert a value with unit `NUMERAL_SYSTEM` it simply shows below error:

`NUMERAL_SYSTEMS is not a valid enum type
'package:units_converter/utils/utils.dart':
Failed assertion: line 80 pos 16: 'false'

When the exception was thrown, this was the stack: 
#2      getPropertyFromEnum (package:units_converter/utils/utils.dart:80:16)
#3      ConvertUnitNum.convertFromTo (package:units_converter/models/extension_converter.dart:8:26)
`

**SOLUTION**
You simply need to add following case in `utils.dart`
`case NUMERAL_SYSTEMS:`
`    return NumeralSystems();`

and add following import: 
`import 'package:units_converter/properties/numeral_systems.dart';`

**Comment by ferraridamiano** [comment]
A minimal reproducible example would be nice

When dealing with numeral systems you should use `String`s and not doubles. Take a look to Example 1 in the readme:
```dart
var octal = '8B'.convertFromTo(NUMERAL_SYSTEMS.hexadecimal, NUMERAL_SYSTEMS.octal);
```

Can we close this issue?

**Comment by krutarth-vaishnav** [comment]
Hi, The data type is not the issue here. I'm passing the string as you shown. As you can see in the error it says
` NUMERAL_SYSTEMS is not a valid enum type`

This error string is coming from the file `utils.dart`

when I inspected why it's throwing this error, I found that it's in the `default :` of `Switch()` 
So basically the type `'NUMERAL_SYSTEM'` is not added in the `Switch case`.

You just need to add it and the issue is resolved as I shown in **Solution** in the description of my Issue.

**Comment by ferraridamiano** [comment]
Could you post a code example?

If you take a closer look to the code you can see that Strings uses a different extensions method which is only for NUMERAL_SYSTEMS. This means that you should never reach that switch by using NUMERAL_SYSTEMS

**Comment by krutarth-vaishnav** [comment]
I got it. I cleaned up everything and pub get again with fresh code example and now its not reaching there. I don't understand why it didn't responded same as before. code is same. This is the code I did.


```
 if(isNumeralConversion){
        convertedString = stringNumber.convertFromTo(_firstUnitName, _secondUnitName);

        convertedString = convertedString == "" ? "0" : convertedString;

        // Convert for Formula
        final convertedValue = "1".convertFromTo(_firstUnitName, _secondUnitName);
        _conversionFormula = "1 $_firstUnitSymbol = $convertedValue $_secondUnitSymbol";
        debugPrint("Converted String : $convertedString");
      }
 else {
        converted = number.convertFromTo(_firstUnitName, _secondUnitName);

        // Convert for Formula
        final convertedValue = 1.convertFromTo(_firstUnitName, _secondUnitName);
        _conversionFormula = "1 $_firstUnitSymbol = $convertedValue $_secondUnitSymbol";
  }

 debugPrint("From : $_firstUnitName, To : $_secondUnitName");
```

Strange thing is I've done it many times before. Anyways thanks for the responses and help.
